{
    "channels": [
        "conda-forge"
    ],
    "dependencies": [
        "python=3.9.23",
        "conda-pack=0.8.1=pyhd8ed1ab_1",
        "xrootd=5.8.1=py39h787ae68_0",
        "root=6.32.10=py39hfcbb7ad_0",
        "conda<2025.1.0",
        "ndcctools>=7.14.7",
        "pip=25.2=pyh8b19718_0",
        "setuptools==70.3.0",
        {
            "pip": [
                "coffea==0.7.26",
                "mt2==1.3.0",
                "xgboost==2.1.4"
            ]
        }
    ],
    "name": "base"
}