#!/usr/bin/env python3
import os
import sys
import cloudpickle
import coffea

if "":
    os.environ['X509_USER_PROXY'] = ""

(fn, args, out) = sys.argv[1], sys.argv[2], sys.argv[3]

with open(fn, 'rb') as f:
    exec_function = cloudpickle.load(f)
with open(args, 'rb') as f:
    exec_args = cloudpickle.load(f)

pickled_out = exec_function(*exec_args)
with open(out, 'wb') as f:
    f.write(pickled_out)

# Force an OS exit here to avoid a bug in xrootd finalization
os._exit(0)
